### ISSUE TITLE
ApplicationAuth controller is not able to update userkey of Application when product.Spec.AuthUserKey() != nil

### ISSUE THREAD

**Issue by vinolipartec** [3scale/3scale-operator#1078]
When:

1. we have a product with:
``` yaml
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: test-product
spec:
  deployment:
    apicastSelfManaged:
      authentication:
        userkey:
          authUserKey: user-key
```
2. we have an application with:
``` yaml
apiVersion: capabilities.3scale.net/v1beta1
kind: Application
metadata:
  name: test-app
spec:
  productCR:
    name: test-product
```
3. we apply:
``` yaml
apiVersion: capabilities.3scale.net/v1beta1
kind: ApplicationAuth
metadata:
  name: test
spec:
  applicationCRName: test-app
  authSecretRef:
    name: test-secret
```

I expect that the userkey of application "test-app" will be updated.

Instead it's not updated.

https://github.com/3scale/3scale-operator/blob/4e7d68b1cc2068d8f78e3506af35f6170c672f66/controllers/capabilities/applicationauth_controller.go#L251-L255
