### ISSUE TITLE
Capabilities: CRDS and relationships

### ISSUE THREAD

**Issue by jmprusi** [3scale/3scale-operator#3]
## Proposal
Let's try to define CRDs and how to handle relationships between them.

### CRD Model

Let's use those primary domain objects as our base:

* **Tenant**: Represents a tenant account. After processing this object, if successful, new credentials secret will be created in the same namespace. Containing accessToken + admin url.
* **Credentials**: This is a secret. Contains the accessToken and admin url to access a 3scale account.
* **Binding**: References a Credentials secret and using a selector, points to API objects services. Those services will use the credentials secret.
* **API**: An API created inside a tenant account
* **Plan**: Plan refers to Limits and has some configuration around cost
* **Limit**: Defines a limit for a metric given a max value and a period
* **Metrics**: A single metric, name and a unit (hit, bytes, request...)
* **IntegrationMethod**: How the API is enforced, via Apicast, CodePlugin... 
* **MappingRules**: Mapping Rules tells the integration method, how to increment metrics based on path

This diagram explains the hierarchy between them, and 1-to-1 or 1-to-many relations : 
```
                               ┌───────────────┐          ┌ ─ ─ ─ ─ ─ ─ ─ ─                     
                               │               │                           │                    
                               │               │ Creates  │  Credentials                        
                               │    Tenant     │─ ─ ─ ─ ─▶      Secret     │                    
                               │               │          │                                     
                               │               │           ─ ─ ─ ─ ─ ─ ─ ─ ┘                    
                               └───────────────┘                   ▲                            
                                                                   │                            
                                                                   │                            
                                                               ObjectRef                        
                                                                   │                            
                                                           ┌───────────────┐                    
                                                           │               │                    
                                                           │    Binding    │                    
                                                           │               │                    
                                                           └───────────────┘                    
                                                                Selector                        
                                                                   │ └───────────────────┐      
                                                                   ▼                     ▼      
                       ┌─────────────────┐                  ┌────────────┐        ┌────────────┐
                       │                 │                  │            │        │            │
       ┌────Selector───│IntegrationMethod│◀───ObjectRef─────│    API     │        │    API     │
       │               │                 │                  │            │        │            │
       │               └─────────────────┘                  └────────────┘        └────────────┘
       │                        │                               │  │ │                   │      
       │           ┌────────────┘                               Selector             Selector   
       │           │   Selector                ┌────────────────┘  │ └─────────────────┐ │      
       │           ▼                           │                   │                   │ │      
       │   ┌──────────────┐                    ▼                   ▼                   ▼ ▼      
       │   │ ┌────────────┴─┐           ┌─────────────┐     ┌─────────────┐     ┌─────────────┐ 
       │   │ │ ┌────────────┴─┐         │ ┌───────────┴─┐   │             │     │             │ 
       │   │ │ │              ├────────▶│ │             │   │    Plan     │     │    Plan     │ 
       │   └─┤ │ MappingRules │─────────┼▶│   Metric    │   │             │     │             │ 
       │     └─┤              │         └─┤             │   └─────────────┘     └─────────────┘ 
       │       └──────────────┘ObjectRef  └─────────────┘          │                   │        
       │               ▲                       ▲ ▲             Selector             Selector    
       │               │                         │                 │                   │        
       │                                       │ │                 ▼                   ▼        
       │               │                         │        ┌─────────────┐       ┌─────────────┐ 
       ▼                                       │ │        │ ┌───────────┴─┐     │             │ 
┌─────────────┐        │                         │        │ │ ┌───────────┴─┐   │             │ 
│ ┌───────────┴─┐       ─ ─ ─ ─                │ │        │ │ │             │   │             │ 
│ │ ┌───────────┴─┐            │                 │        └─┤ │    Limit    │   │             │ 
│ │ │             │                            │ │          └─┤             │   │     ...     │ 
└─┤ │  Policies   │            │                 │            └─────────────┘   │             │ 
  └─┤             │                            │ │                   │          │             │ 
    └─────────────┘         Creates              │                   │          │             │ 
                                               │ └────ObjectRef──────┘          │             │ 
                               │                                                └─────────────┘ 
                     ┌───────────────────┐     │                                                
                     │                   │  Creates                                             
                     │                   │     │                                                
                     │  OpenAPIDocument  │─ ─ ─                                                 
                     │                   │                                                      
                     │                   │                                                      
                     └───────────────────┘                                                                                                                                               
```

So, we need to find a way to correctly reference one CRD with another and make it easier to allow the user to create overrides for multiple environments, and add some discoverability to new objects. 

#### Proposal 1: Hierarchy model, with selectors and ObjectReference 

Let's try to respect the initial hierarchy model, top-down, and use available kubernetes types as Selectors and [ObjecReference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#ownerreference-v1-meta). 

Using **IntegrationMethod**, **bindings**, **metrics**, **limits** , **plans** and **APIs**: 

```yaml
apiVersion: api.3scale.net/v1alpha1
kind: BINDING
metada:
  name: mySaaSAccount
spec:
  SecretRef:
    name: MySecret
  APISelector:
    matchLabels:
       environment: production
----
apiVersion: api.3scale.net/v1alpha1
kind: API
metadata:
  name: myapi
  labels:
     environment: production
spec:
  description: "3scale service for my awesome api"
  integrationMethodRef: apicastIntegration
  PlanSelector:
    matchLabel: 
      environment: production
      api: myapi
  metricSelector:
    matchLabel: 
      api: myapi
  # This object requires more fields for defining the integration method and other settings.
----
apiVersion: api.3scale.net/v1alpha1
kind: INTEGRATIONMETHOD
metadata:
  name: apicastIntegration
  labels:
    api: myapi
spec:
  apicastOnPrem:
    privateBaseURL: https://echo-api.3scale.net:443
    stagingPublicBaseURL: https://api.testing.com
    productionPublicBaseURL: https://api.testing.com
    apiTestGetRequest: /
    authenticationSettings:
      hostHeader: testing.com
      secretToken: Shared_secret_sent_from_proxy_to_API_backend_9603f637ca51ccfe
      credentials:
        apiKey:
          authParameterName: user_key
          credentialsLocation: header / query
      errors:
        authenticationFailed:
          responseCode: 403
          contentType: "text/plain; charset=us-ascii"
          responseBody: "Authentication failed"
        authenticationMissing:
          responseCode: 404
          contentType: "text/plain; charset=us-ascii"
          responseBody: "No Mapping Rule matched"          
    mappingRulesSelector:
      matchLabels:
        api: myapi
#    policiesSelector:
#      matchLabels:
#       api: myapi
----
apiVersion: api.3scale.net/v1alpha1
kind: MAPPINGRULE
metadata:
  name: list_apps
  labels:
    api: myapi
spec:
  path: /apps/
  method: GET
  increment: 1
  metricRef:
    name: list_apps
----
apiVersion: api.3scale.net/v1alpha1
kind: PLAN
metadata:
  name: basic
  labels:
    environment: production
    api: myapi
spec:
  trialPeriod: 10
  aprovalRequired: true
  costs:
    setupFee: 0
    costMonth: 10
  limitSelector:
    matchLabels:
      plan: basic
----
apiVersion: api.3scale.net/v1alpha1
kind: METRIC
metadata:
  name: list_apps
  labels:
    api: myapi
spec:
  description: "Example method" 
  unit: hit
  incrementHits: true
----
apiVersion: api.3scale.net/v1alpha1
kind: METRIC
metadata:
  name: create_app
  labels:
    api: myapi
spec:
  unit: hit 
  description: "Example metric" 
----
apiVersion: api.3scale.net/v1alpha1
kind: LIMIT
metadata:
  name: list_apps_eternity_100
  labels:
    plan: basic
spec:
  metric:
    name: list_apps
  description: "Limit for list_apps in basic plan"
  period: enternity
  maxValue: 100
---- 
apiVersion: api.3scale.net/v1alpha1
kind: LIMIT
metadata:
  name: list_apps_month_1
  labels:
    api: myapi
    plan: basic
spec:
  metric:
    name: list_apps
  description: "Limit for list_apps in basic plan"
  period: month
  maxValue: 1
```

The important bits are: 

How limits relate to metrics, a 1-to-1 relationship: 
```yaml
  metric:
    name: list_apps
```
this is using the [ObjectReference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#objectreference-v1-core) type from kubernetes.

How the application plan includes all the desired limits:
```yaml
  limitSelector:
    matchLabels:
      plan: basic
```
This one, on the other hand, uses a [label selector](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#labelselector-v1-meta), will include as limits, all the ones that match the desired labels. In this case, the `plan`  label with a value of `basic`.

We are doing the same to relate applicationPlans and Metrics to a Service:

```yaml
  applicationPlanSelector:
    matchLabel: 
      environment: production
      api: myapi
  metricSelector:
    matchLabel: 
      api: myapi
```

### Controllers: 

Deciding on how many controllers we want to use, will change how the relationship between objects is done... 

#### One Controller for each CRD

One controller for each CRD has a small problem, each controller only sees a piece of the global configuration, not knowing who references the controlled objects, one way to avoid that is to add proper OwnerReferences on each controller run, for example: 

* **Tenant Controller**: Tenant Object will add itself as the Owner of the Service object based on a tenant selector.
* **API Controller**: API will add itself as the owner of metrics, and application plans based on proper selectors.
* **Metric controller**: Will trigger and create the metric using the OwnerReference field, to find the required information (Tenant and Service). 
* **All the other CRDs** ... 

This way, each controller can trace up to the tenant level and get the required info.

#### Two Controllers with an internal "consolidated" CRD.

Trying to simplify relationships between CRDs, and overall complexity, using only two controllers:

* **Consolidating controller**: reading the current state from those multiple CRDs, persisting all of them into an internal state CRD, only accessible by the Operator, that integrates all the small CRDs into a single one. (We can use [OwnerReferences](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#ownerreference-v1-meta) so we can use the kubernetes tooling to show orphaned objects, or even GC them.) 

* **Reconciliation controller**: Reading the internal consolidated CRD and reconcile directly with the 3scale API.

This model allows us to control and reduce the number of times we reconcile with the 3scale API. 

A consolidated object could look like:

```yaml
apiVersion: api.internal.3scale.net/v1alpha1
kind: THREESCALECONFIG
metadata:
  name: threescaleConfig
spec:
    tenants:
    - name: myTenant
    APIs:
    - name: myAPI
      description: cacafuti
      credentials:
      - accessToken: AAAAAAAAAAAAAAAAAAAAAAAA
        adminURL: https://my-admin.3scale.net:443/
      integration:
          apicastOnPrem:
            privateBaseURL: https://echo-api.3scale.net:443
            stagingPublicBaseURL: https://api.testing.com
            productionPublicBaseURL: https://api.testing.com
            apiTestGetRequest: /
            authenticationSettings:
              hostHeader: testing.com
              secretToken: Shared_secret_sent_from_proxy_to_API_backend_9603f637ca51ccfe
              credentials:
                  apiKey:
                    authParameterName: user_key
                    credentialsLocation: header / query
            errors:
              authenticationFailed:
                responseCode: 403
                contentType: "text/plain; charset=us-ascii"
                responseBody: "Authentication failed"
              authenticationMissing:
                responseCode: 404
                contentType: "text/plain; charset=us-ascii"
                responseBody: "No Mapping Rule matched"
            mappingRules:
              - name: list_apps
                path: /apps/
                method: GET
                increment: 1
                metric: list_apps
      metrics:
      - name: list_apps
        unit: hit
        description: list apps metrics
      - name: get_apps
        unit: hit
        description: get apps
      Plans:
      - name: basic
        trialPeriodDays: 10
        approvalRequired: true
        costs:
          setupFee: 0
          costMonth: 10
        limits:
          - name: list_apps_month_1
            description: "Limit for list_apps in basic plan"
            period: month
            maxValue: 1
            metric: list_apps
          - name: get_apps_day
            description: "Limit for get_apps in basic plan"
            period: day
            maxValue: 100
            metric: get_apps
```

#### OpenAPIDocument

```yaml
apiVersion: api.3scale.net/v1alpha1
kind: OPENAPIDOCUMENT
metadata:
  name: myOpenAPISpec
spec:
  metricLabels:    #Labels to add to the generated Objects
    - api: myApi
  mappingRuleLabels:  #Labels to add to the generated Objects
    - api: myapi
  Definition: |
    openapi: "3.0.0"
    info:
      title: Simple API overview
      version: 2.0.0
    paths:
      /test:
        get:
          operationId: metricsA
          summary: List Objects
        post:
          operationId: metricsB
          summary: Create Object
```

#### IntegrationMethod 

The integration Method object is "complex", here you can see 3 full examples of the possible 3scale integrations, "Apicast On Prem", "Apicast Hosted" and "Code Plugin": 

```yaml
apiVersion: api.3scale.net/v1alpha1
kind: INTEGRATIONMETHOD
metadata:
  name: apicastIntegration
  labels:
    api: myapi
spec:
  apicastOnPrem:
    privateBaseURL: https://echo-api.3scale.net:443
    stagingPublicBaseURL: https://api.testing.com
    productionPublicBaseURL: https://api.testing.com
    apiTestGetRequest: /
    authenticationSettings:
      hostHeader: testing.com
      secretToken: Shared_secret_sent_from_proxy_to_API_backend_9603f637ca51ccfe
      credentials:
        apiKey:
          authParameterName: user_key
          credentialsLocation: header / query
        appID:
          appIDParameterName: "app_id"
          appKeyParameterName: "app_key"
          credentialsLocation: header / query
        openIDConnector:
          issuer: http://sso.example.com/auth/realms/gateway
          credentialsLocation: header / query
      errors:
        authenticationFailed:
          responseCode: 403
          contentType: "text/plain; charset=us-ascii"
          responseBody: "Authentication failed"
        authenticationMissing:
          responseCode: 404
          contentType: "text/plain; charset=us-ascii"
          responseBody: "No Mapping Rule matched"          
    mappingRulesSelector:
      matchLabels:
        api: myapi
    policiesSelector:
      matchLabels:
        api: myapi
---
apiVersion: api.3scale.net/v1alpha1
kind: INTEGRATIONMETHOD
metadata:
  name: apicastIntegration
  labels:
    api: myapi
spec:
  apicastHosted:
    privateBaseURL: https://echo-api.3scale.net:443
    apiTestGetRequest: /
    authenticationSettings:
      hostHeader: testing.com
      secretToken: Shared_secret_sent_from_proxy_to_API_backend_9603f637ca51ccfe
      credentials:
        apiKey:
          authParameterName: user_key
          credentialsLocation: header / query
        appID:
          appIDParameterName: "app_id"
          appKeyParameterName: "app_key"
          credentialsLocation: header / query
      errors:
        authenticationFailed:
          responseCode: 403
          contentType: "text/plain; charset=us-ascii"
          responseBody: "Authentication failed"
        authenticationMissing:
          responseCode: 404
          contentType: "text/plain; charset=us-ascii"
          responseBody: "No Mapping Rule matched"          
    mappingRulesSelector:
      matchLabels:
        api: myapi
    policiesSelector:
      matchLabels:
        api: myapi
---
apiVersion: api.3scale.net/v1alpha1
kind: INTEGRATIONMETHOD
metadata:
  name: codePlugin
  labels:
    api: myapi
spec:
  codePlugin:
    authenticationSettings:
      credentials:
        apiKey:
        appID:
        openIDConnector:
```

------
Changelog:
``` 
23/11/18 - Updated using ObjectReferences instead of custom field for limits -> metrics
          - Added new object, service and how it should relate to other components
          - Updated diagram to fix a mistake. Metrics are created at a service level.
26/11/18 - Added new proposals around Controllers. 
27/11/18 - Added new object to represent credentials, `Binding` and `Credentials`, changed the relationship with the `tenant` object. Now this design can work with a 3scale SaaS Account. 
28/11/18 - Added new objects: Mapping Rules, and Integration Method.  
29/11/18 - Added new CRD object "OpenAPIDocument"
03/12/18 - Consolidated object:  Credentials are now part of the API

```

**Comment by maleck13** [comment]
This may also be useful https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#objectreference-v1-core to look at. Although I have not used it directly myself yet. It is used in several k8s objects.

**Comment by jmprusi** [comment]
If we use an (local?)ObjectReference instead of a simple name reference: 

```
apiVersion: api.3scale.net/v1alpha1
kind: LIMIT
metadata:
  name: list_apps_month_1
  labels:
    plan: basic
spec:
  metric:
    name: list_apps
  description: "Limit for list_apps in basic plan"
  period: month
  maxValue: 1
```
