### ISSUE TITLE
Product CRD security spec's attribute SecretToken as k8s secret reference instead of open field

### ISSUE THREAD

**Issue by eguzki** [3scale/3scale-operator#507]
Security Spec of the product has one attribute called Secret Token and it is an open field. 

```
spec:
    backendUsages:
      swagger_petstore:
        path: /
    deployment:
      apicastHosted:
        authentication:
          userkey:
            security:
              secretToken: MyCustomSecretToken
```

It should be secret reference instead of open field
