### ISSUE TITLE
3scale install fails on Azure RedHat OpenShift [ARO] 4.5

### ISSUE THREAD

**Issue by ezYakaEagle442** [3scale/3scale-operator#547]
Following RedHat [3scale install doc on OpenShift](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.9/html/installing_3scale/install-threescale-on-openshift-guide#deploying-threescale-using-the-operator), it is mentionned

1. Persistent volumes

- 1. RWO (ReadWriteOnce) persistent volumes for Redis and MySQL persistence
- 2. **RWX (ReadWriteMany) persistent volume for CMS and System-app Asset**s

2.  "Note: OCP 4 supports deployment of 3scale using the operator only"

The 3Scale [APIM Supported Configurations](https://access.redhat.com/articles/2798521) shows

1. OCP 4.5 & 4.6 are supported, ==> is ARO 4.5 & 4.6 also supported ?
2. 3scale API Management 2.9 System component has been tested and it’s supported with the following file storage configurations:
File storage
- Persistent Volume Claims (PVC) with RWX access mode* ( NFS is not a suitable storage for production environments.)
- Amazon Simple Storage Service (S3) compatible storages

When installing it through the Operator Hub in Azure RedHat OpenShift [ARO] 4.5, the installation fails as the System-Storage PVC has been created in RWO, failing with error : "_Failed to provision volume with Storage Class "managed-premium: invalid AccessModes [ReadWriteMany]": only AccessModes [ReadWriteOnce] are supported_"

This managed-premium storage-class is the default one created in ARO leveraing the [in-tree Azure disk plugin]([url](https://kubernetes.io/docs/concepts/storage/volumes/#azuredisk)) which does not support RWX as far as I know :
```
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

[ARO4 supports the CSI drivers](https://docs.openshift.com/aro/4/storage/persistent_storage/persistent-storage-csi.html) and I have already sucessfully tested them, see my repo at [https://github.com/ezYakaEagle442/aro-pub-storage](https://github.com/ezYakaEagle442/aro-pub-storage)

The [Azure Disk CSI Driver supports Multi-Node Read Write with RWX](https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/sharedisk#shared-diskmulti-node-readwrite) :
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS  # Currently shared disk only available with premium SSD
  maxShares: "2"
  cachingMode: None  # ReadOnly cache is not available for premium SSD with maxShares>1
reclaimPolicy: Delete
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Gi  # minimum size of shared disk is 256GB (P15)
  volumeMode: Block
  storageClassName: managed-csi 
```
 
The [CSI Azure  File drivers](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md) and the [Azure Blob Storage CSI driver](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/e2e_usage.md) support as well RWX .

So could you please fix the installation failure on ARO :

1. Stating that the CSI drivers are required, therefore its installation is needed as a pre-req
2. Update the System-Storage PVC  to **managed-csi** or **file.csi.azure.com** or **blob.csi.azure.com**
