### ISSUE TITLE
Increase backend-cron Memory limits

### ISSUE THREAD

**Issue by krishvoor** [3scale/3scale-operator#672]
OOMKilled backend-cron on ppc64le, this behaviour is observed when a pod with a smaller footprint ( memory ) is spun on ppc64le, this is because of bigger PAGESIZE on ppc64le ( 64K ). More details on how this results into OOMKilled can be found [here](https://cloudgeekz.medium.com/oomkilled-containers-and-number-of-cpus-b6c78680ac3) 

In our investigation, we found that, increasing the memory resource, allowed us to deploy the 3scale product.

```
backend:
  cronSpec:
     resources:
      requests:
         memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "400Mi"
        cpu: "500m"
```
