### ISSUE TITLE
CRD and admin-UI out of sync

### ISSUE THREAD

**Issue by mrunesson** [3scale/3scale-operator#688]
I am running the 3Scale operator 0.7.0 on OpenShift 4.8.18 (k8s 1.21).

I tried the following scenario.

I created a backend via CRD
```
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: echocrd
spec:
  name: "Echo CRD"
  systemName: "echocrd"
  privateBaseURL: "http://echo.runmm-echo"
```

I go to the admin UI and verify the backend is shown.

The I change in UI the privateBaseURL of my service to `http://foo`

Last, I do a `kubectl get backend -o yaml echocrd` and expect that privateBaseURL is `http://foo`. 
Instead it is still `http://echo.runmm-echo`. Admin UI shows the new URL.

This basically mean that I cannot use a gitops flow. If someone do a change in UI the setup reported
by the CRD and admin UI will be out of sync.

Anyone has a solution for this?
