### ISSUE TITLE
Unable to install 3scale

### ISSUE THREAD

**Issue by pre-yein** [3scale/3scale-operator#705]
Hello, I want to install 3scale on my Openshift cluster.
OCP version is 4.9.10
The namespace where I want to deploy 3scale is "3scale".

I want to know how to provide my OCP cluster RWX (ReadWriteMany) persistent volume storage class. 
I installed OCP by CRC in an on-premise VM, and tried to configure NFS. I understand that I have to create the storage class. 
After creating ServiceAccount,  ClusterRole, ClusterBinding, Deployment and StorageClass, I created APIManager through the operator by specifying "managed-nfs-storage" as StorageClass. But if failed.

My question is:
When NFS is mounted on the path "localhost:/data/NFS", Is it correct to create ServiceAccount,  ClusterRole, ClusterBinding, Deployment and StorageClass in sequence as specified in the yaml file below?
Is there anything wrong or unnecessary? 

serviceaccount.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
```

clusterrole.yaml
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["nfs-provisioner"]
    verbs: ["use"]
```

clusterbinding.yaml
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    namespace: 3scale
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nfs-provisioner-otherRoles
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nfs-provisioner-otherRoles
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    namespace: 3scale
roleRef:
  kind: Role
  name: nfs-provisioner-otherRoles
  apiGroup: rbac.authorization.k8s.io
```

deployment-nfs.yaml
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: localhost
            - name: NFS_PATH
              value: /data/NFS
      volumes:
        - name: nfs-client-root
          nfs:
            server: localhost
            path: /data/NFS
```

storageclass-nfs.yaml
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: managed-nfs-storage 
provisioner: fuseim.pri/ifs
```
I referencd the link below.
https://ccambo.tistory.com/entry/Kubernetes-Storage-CentOS-8%EC%97%90-Dynamic-NFS-Client-Provisioner-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0

Thank you.

**Comment by eguzki** [comment]
I have never gone through that. For 3scale testing, I recommend starting with the s3 based deployment https://github.com/3scale/3scale-operator/blob/master/doc/operator-user-guide.md#s3-filestorage-installation

**Comment by YoungEun-IN** [comment]
> I have never gone through that. For 3scale testing, I recommend starting with the s3 based deployment https://github.com/3scale/3scale-operator/blob/master/doc/operator-user-guide.md#s3-filestorage-installation
> 
> With the s3 deployment, no RWX storage class is needed.

Thanks for your reply.
I tried s3 deployment. but failed.

I created secret.
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-auth
stringData:
  AWS_ACCESS_KEY_ID: **********
  AWS_SECRET_ACCESS_KEY: ************
  AWS_BUCKET: ********
  AWS_REGION: ap-northeast-2
type: Opaque
```
![image](https://user-images.githubusercontent.com/46465928/149190247-34cc4c89-fbe2-4c6c-81fb-36256a5a95e8.png)

and created apimanaer.
```
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: example-apimanager
spec:
  wildcardDomain: lvh.me
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: aws-auth
```
![화면 캡처 2022-01-13 020740](https://user-images.githubusercontent.com/46465928/149189618-e8c239f8-056c-4132-821d-23a04ea88edc.png)


![image](https://user-images.githubusercontent.com/46465928/149186389-1293694d-bb82-42b2-94dc-8d95bd194a3c.png)

```
[admin@localhost tmp]$ oc get pods
NAME                                                         READY   STATUS             RESTARTS        AGE
apicast-production-1-deploy                                  1/1     Running            0               23m
apicast-production-1-jp7h5                                   0/1     Init:0/1           0               22m
apicast-staging-1-deploy                                     0/1     Completed          0               23m
apicast-staging-1-jb6zv                                      1/1     Running            0               17m
backend-cron-1-deploy                                        0/1     Error              0               23m
backend-listener-1-deploy                                    0/1     Completed          0               23m
backend-listener-1-nfsxz                                     0/1     Pending            0               17m
backend-redis-1-deploy                                       0/1     Error              0               23m
backend-worker-1-deploy                                      0/1     Error              0               23m
system-app-1-deploy                                          1/1     Running            0               23m
system-app-1-hook-pre                                        1/1     Running            0               23m
system-memcache-1-deploy                                     0/1     Completed          0               23m
system-memcache-1-jgxpt                                      1/1     Running            0               7m7s
system-mysql-1-deploy                                        0/1     Error              0               23m
system-redis-1-deploy                                        0/1     Error              0               23m
system-sidekiq-1-deploy                                      0/1     Error              0               23m
system-sphinx-1-deploy                                       0/1     Error              0               23m
threescale-operator-controller-manager-v2-7b4d966ccb-v2gt8   1/1     Running            1 (5h14m ago)   5h40m
zync-1-deploy                                                0/1     Error              0               23m
zync-database-1-deploy                                       0/1     Error              0               23m
zync-que-1-deploy                                            0/1     Completed          0               23m
zync-que-1-qmhhm                                             0/1     CrashLoopBackOff   8 (2m21s ago)   23m
[admin@localhost tmp]$
```

![image](https://user-images.githubusercontent.com/46465928/149189446-a9bd4716-e9ce-4830-ade6-db5889b63e91.png)

Can I know what was wrong? Any sugesstion?

Thank you.

**Comment by YoungEun-IN** [comment]
> I have never gone through that. For 3scale testing, I recommend starting with the s3 based deployment https://github.com/3scale/3scale-operator/blob/master/doc/operator-user-guide.md#s3-filestorage-installation
> 
> With the s3 deployment, no RWX storage class is needed.

Thanks for your reply.
I tried s3 deployment. but failed.

I created secret.
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-auth
stringData:
  AWS_ACCESS_KEY_ID: **********
  AWS_SECRET_ACCESS_KEY: ************
  AWS_BUCKET: ********
  AWS_REGION: ap-northeast-2
type: Opaque
```
![image](https://user-images.githubusercontent.com/46465928/149190247-34cc4c89-fbe2-4c6c-81fb-36256a5a95e8.png)

and created apimanaer.
```
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: example-apimanager
spec:
  wildcardDomain: lvh.me
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: aws-auth
```
![화면 캡처 2022-01-13 020740](https://user-images.githubusercontent.com/46465928/149189618-e8c239f8-056c-4132-821d-23a04ea88edc.png)


![image](https://user-images.githubusercontent.com/46465928/149186389-1293694d-bb82-42b2-94dc-8d95bd194a3c.png)

```
[admin@localhost tmp]$ oc get pods
NAME                                                         READY   STATUS             RESTARTS        AGE
apicast-production-1-deploy                                  1/1     Running            0               23m
apicast-production-1-jp7h5                                   0/1     Init:0/1           0               22m
apicast-staging-1-deploy                                     0/1     Completed          0               23m
apicast-staging-1-jb6zv                                      1/1     Running            0               17m
backend-cron-1-deploy                                        0/1     Error              0               23m
backend-listener-1-deploy                                    0/1     Completed          0               23m
backend-listener-1-nfsxz                                     0/1     Pending            0               17m
backend-redis-1-deploy                                       0/1     Error              0               23m
backend-worker-1-deploy                                      0/1     Error              0               23m
system-app-1-deploy                                          1/1     Running            0               23m
system-app-1-hook-pre                                        1/1     Running            0               23m
system-memcache-1-deploy                                     0/1     Completed          0               23m
system-memcache-1-jgxpt                                      1/1     Running            0               7m7s
system-mysql-1-deploy                                        0/1     Error              0               23m
system-redis-1-deploy                                        0/1     Error              0               23m
system-sidekiq-1-deploy                                      0/1     Error              0               23m
system-sphinx-1-deploy                                       0/1     Error              0               23m
threescale-operator-controller-manager-v2-7b4d966ccb-v2gt8   1/1     Running            1 (5h14m ago)   5h40m
zync-1-deploy                                                0/1     Error              0               23m
zync-database-1-deploy                                       0/1     Error              0               23m
zync-que-1-deploy                                            0/1     Completed          0               23m
zync-que-1-qmhhm                                             0/1     CrashLoopBackOff   8 (2m21s ago)   23m
[admin@localhost tmp]$
```

![image](https://user-images.githubusercontent.com/46465928/149189446-a9bd4716-e9ce-4830-ade6-db5889b63e91.png)

Can I know what was wrong? Any sugesstion?

Thank you.
