### ISSUE TITLE
Unable to install 3scale with s3 deployment

### ISSUE THREAD

**Issue by pre-yein** [3scale/3scale-operator#706]
Hello, I want to install 3scale in my OCP on-premise VM environment.

I tried s3 deployment.  but failed.

OCP version is 4.9.10
CPU is 8vCPU
Memory is 16G
HDD is 150G.

![image](https://user-images.githubusercontent.com/49935588/149251834-bb279fc7-2584-469e-b370-93fbb8ff5641.png)

I created secret.
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-auth
stringData:
  AWS_ACCESS_KEY_ID: **********
  AWS_SECRET_ACCESS_KEY: ************
  AWS_BUCKET: ********
  AWS_REGION: ap-northeast-2
type: Opaque
```
![image](https://user-images.githubusercontent.com/46465928/149190247-34cc4c89-fbe2-4c6c-81fb-36256a5a95e8.png)

and created apimanaer.
```
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: example-apimanager
spec:
  wildcardDomain: lvh.me
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: aws-auth
```
![화면 캡처 2022-01-13 020740](https://user-images.githubusercontent.com/46465928/149189618-e8c239f8-056c-4132-821d-23a04ea88edc.png)

![image](https://user-images.githubusercontent.com/46465928/149186389-1293694d-bb82-42b2-94dc-8d95bd194a3c.png)

```
[admin@localhost tmp]$ oc get pods
NAME                                                         READY   STATUS             RESTARTS        AGE
apicast-production-1-deploy                                  1/1     Running            0               23m
apicast-production-1-jp7h5                                   0/1     Init:0/1           0               22m
apicast-staging-1-deploy                                     0/1     Completed          0               23m
apicast-staging-1-jb6zv                                      1/1     Running            0               17m
backend-cron-1-deploy                                        0/1     Error              0               23m
backend-listener-1-deploy                                    0/1     Completed          0               23m
backend-listener-1-nfsxz                                     0/1     Pending            0               17m
backend-redis-1-deploy                                       0/1     Error              0               23m
backend-worker-1-deploy                                      0/1     Error              0               23m
system-app-1-deploy                                          1/1     Running            0               23m
system-app-1-hook-pre                                        1/1     Running            0               23m
system-memcache-1-deploy                                     0/1     Completed          0               23m
system-memcache-1-jgxpt                                      1/1     Running            0               7m7s
system-mysql-1-deploy                                        0/1     Error              0               23m
system-redis-1-deploy                                        0/1     Error              0               23m
system-sidekiq-1-deploy                                      0/1     Error              0               23m
system-sphinx-1-deploy                                       0/1     Error              0               23m
threescale-operator-controller-manager-v2-7b4d966ccb-v2gt8   1/1     Running            1 (5h14m ago)   5h40m
zync-1-deploy                                                0/1     Error              0               23m
zync-database-1-deploy                                       0/1     Error              0               23m
zync-que-1-deploy                                            0/1     Completed          0               23m
zync-que-1-qmhhm                                             0/1     CrashLoopBackOff   8 (2m21s ago)   23m
[admin@localhost tmp]$
```

![image](https://user-images.githubusercontent.com/46465928/149189446-a9bd4716-e9ce-4830-ade6-db5889b63e91.png)

Can I know what was wrong? Any sugesstion?
Please help me.

Thank you.

**Comment by eguzki** [comment]
By default, 3scale deploymentconfigs are crated with [resource requirements](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/). Your pods are complaining because insufficient memory. Resource requirements is a mechanism to ensure that the deployed 3scale meets minimum performance needs. 

You can disable resource requirements;
```
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: example-apimanager
spec:
  wildcardDomain: lvh.me
  resourceRequirementsEnabled: false
```
