### ISSUE TITLE
Allow use of IRSA for s3 bucket configurations

### ISSUE THREAD

**Issue by dlydiard** [3scale/3scale-operator#820]
Instead of providing credentials for the s3 bucket, we would like to take advantage of IRSA with OpenShift
https://docs.openshift.com/rosa/rosa_architecture/rosa-sts-about-iam-resources.html

long-lived aws credentials are not desired.

**Comment by eguzki** [comment]
Thanks for the request. 

Is it about the STS authentication for S3 as defined in [3scale operator doc about s3 with STS](https://github.com/3scale/3scale-operator/blob/master/doc/operator-user-guide.md#manual-mode-with-sts) and implemented in https://github.com/3scale/3scale-operator/pull/792 ? Jira issue https://issues.redhat.com/browse/THREESCALE-8772

**Comment by dlydiard** [comment]
It might be possible to point the `AWS_WEB_IDENTITY_TOKEN_FILE` secret value to the resulting token provisioned with IRSA. 

However, i still think the `APIManager` config can support IRSA in a more direct fashion. For example:
```
    fileStorage:
      simpleStorageService:
        irsa:
          enabled: true
          audience: sts.amazonaws.com
          roleArn: arn:aws:iam::....
```

I would then expect the operator to add the needed annotations on the appropriate `ServiceAccounts` to enable IRSA.
