### ISSUE TITLE
Support Deployments plus Node Anti Affinity

### ISSUE THREAD

**Issue by dlydiard** [3scale/3scale-operator#828]
`DeploymentConfig` does not support node anti affinity for PODs with kube > 1.6. Can the DeploymentConfigs be converted to use `Deployment`'s instead, so that anti affinity can be used? We want to guarantee the PODs are spread across AZs for some of the sub systems.

**Comment by dlydiard** [comment]
Update i was able to get this to work, i had an indentation issue... 

```
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
...
spec:
  apicast:
    productionSpec:
      affinity:
        podAntiAffinity:
          ...
                topologyKey: kubernetes.io/hostname
```
