### ISSUE TITLE
OpenAPI CRD: support for OIDC sec requirement

### ISSUE THREAD

**Issue by eguzki** [3scale/3scale-operator#842]
### What

Currently, 3scale Operator's OpenAPI controller supports [OpenAPI 3.0.2 specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md) with the `apiKey` security scheme. This is about adding support for `openIdConnect` **and** `oauth2` [Security Requirement Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#security-requirement-object) on OpenAPI documents referenced by the OpenAPI CR.

Jira: https://issues.redhat.com/browse/THREESCALE-9884

### Design overview

New fields will be added to the OpenAPI CRD to support the `openIdConnect` and `oauth2` sec scheme type in order to configure 3scale product with  OpenIDConnect authentication mode. 3scale requires some bits of information that are not included in the OpenAPI spec, therefore those bits need to be provided in the OpenAPI CR. Specifically: 
* `OpenID Connect Issuer Type` which will default to `rest` but can be overridden from the OpenAPI CR
* `OpenID Connect Issuer`. 3scale requires that the issuer URL must include a client secret. 
* `flows` object. When the sec scheme is `oauth2`, the flows are provided by the OpenAPI doc. However, for `openIdConnect` security scheme, the OpenAPI doc does not provide the flows. In that case, the OpenAPI CR can provide those.

The new OpenAPI CRD would look like this

```yaml
apiVersion: capabilities.3scale.net/v1beta1
kind: OpenAPI
metadata:
  name: openapi1
spec:
  oidc:  // optional field
    issuerType:  // optional field. Valid values: [keycloak, rest]. Defaults to `rest`.
    issuer: "https://some-secret@example.com/auth/realms/petstore"   // Required field
    flows:   // optional field. Only valid for `openIdConnect` sec scheme
       standardFlowEnabled: false   // optional field
       implicitFlowEnabled: false   // optional field
       serviceAccountsEnabled: false   // optional field
       directAccessGrantsEnabled: false   // optional field
  ....
  openapiRef:
    secretRef:
      name: oidc-openapi-secret
  ....
```

When the referenced OpenAPI spec's sec scheme is `openIdConnect` or `oauth2`, the `spec.oidc` must not be `nil`. The openapi controller will validate this and flag the resource as invalid if `spec.oidc` is empty or `nil`.

### Technical details

The Product CRD (and its controller) already supports the OIDC authentication mode, so no changes required there.

Some considerations:
* `credentials location` is hard-coded to `headers`.
* `status` section should report as invalid when there is no `spec.oidc` section and the openapi document's sec scheme is `openIdConnect` or `oauth2`.
* For `oauth2`, the AUTHORIZATION FLOW is read from the [flows](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#security-scheme-object) field of the security scheme object.
* For `openIdConnect`, the AUTHORIZATION FLOW is read from the OpenAPI CR `spec.oidc.flows`

###  Open questions
* What should the operator do with the [list of scope names](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#security-requirement-object)?? 
```yaml
---
openapi: "3.0.2"
security:
    - petstore_oidc:
      - write:pets
      - read:pets
  components:
    securitySchemes:
      petstore_oidc:
        type: openIdConnect
        flows:
          clientCredentials:
            tokenUrl: http://example.org/api/oauth/dialog
            scopes:
              write:pets: modify pets in your account
              read:pets: read your pets
```

* `JwtClaimWithClientID` and `JwtClaimWithClientIDType` 3scale attributes can be read from the OpenAPI doc or should be provided (optionally) from the OpenAPI CR?

**Comment by andrewdavidmackenzie** [comment]
Can multiple flows be enabled at the same time, hence the multiple boolean fields?
(otherwise a selector of the flow in a single field would do).
Is that the canonical way to do that in Yaml (and CRs) (I honestly don't know).

**Comment by valerymo** [comment]
Hi @eguzki   in my draft, I suggested - CRD to have same names convention / structure as OpenAPI-Specification. 
This is example of my CRD, that used in [837](https://github.com/3scale/3scale-operator/pull/837)
```
apiVersion: capabilities.3scale.net/v1beta1
kind: OpenAPI
metadata:
  generation: 1
  name: openapi-example
spec:
  openapiRef:
    url: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml
  securityScheme:
    type: openIdConnect
    openIdConnectUrl: https://3scale-zync:vgDhfCZGAUKb7ixdI1w1f1LWcEbAVNQW@keycloak-rhsso-test.apps.vmogilev01.giq5.s1.devshift.org/auth/realms/petstore
    flows:
      standardFlowEnabled: false
      implicitFlowEnabled: false
```
We have here: securityScheme , where `type: openIdConnect` is one of available schemes, + Flows, etc. It's same as in [OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#security-requirement-object). This was my approach. I understand that it's differ from current design, where ApiKey, that is one of  securitySchemes types) is defined differ.
