### ISSUE TITLE
Can't install 3Scale Operator 

### ISSUE THREAD

**Issue by am90670** [3scale/3scale-operator#941]
Hi,

I'm trying to install and configure the Red Hat 3Scale Operator v0.11.11 in a ROSA v4.13 cluster.  The pod created by the deployment config `zync-que` is in a `CrashLoopBackoff` state and is reporting the error in its log:

```
...
Que waiting for jobs...
#<Thread:0x00007fac65cfa300 /opt/zync/vendor/bundle/ruby/3.1.0/gems/que-2.2.1/lib/que/locker.rb:179 run> terminated with exception (report_on_exception is true):
/opt/zync/vendor/bundle/ruby/3.1.0/gems/que-2.2.1/lib/que/connection.rb:63:in `exec': ERROR: column "id" not found in data type que_jobs (PG::UndefinedColumn)
LINE 14: SELECT pg_try_advisory_lock((job).id) AS tak...
...
```

How do I resolve this issue? 

External PostgreSQL 13.13 databases are configured for the system and zync databases.

APIManager Custom resoure:

```
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: threescale-apimanager
  namespace: 3scale
spec:
  externalComponents:
    backend:
      redis: false
    system:
      database: true
      redis: false
    zync:
      database: true
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: efs-dynamic
  wildcardDomain: ....
```
